controllers:
    resource: ../src/Controller/
    type: attribute

contact_controller:
    path: /contact
    controller: App\Controller\ContactController::loadTemplate

home_controller:
    path: /home
    controller: App\Controller\HomeController::loadTemplate

company_controller:
    path: /company
    controller: App\Controller\CompanyController::loadTemplate

company_controller_add:
    path: /company/add
    controller: App\Controller\CompanyController::addCompany