controllers:
    resource: ../src/Controller/
    type: attribute

company_controller:
    path: /company
    controller: App\Controller\CompanyController::loadTemplate

company_controller_add:
    path: /company/addCompany
    controller: App\Controller\CompanyController::addCompany
    methods: POST

company_controller_read:
    path: /company/readCompany/
    controller: App\Controller\CompanyController::readCompany
    methods: GET

company_controller_readbyid:
    path: /company/readCompany/id/{id}
    controller: App\Controller\CompanyController::readCompanyByID
    methods: GET

company_controller_readbyName:
    path: /company/readCompany/name/{name}
    controller: App\Controller\CompanyController::readCompanyByName
    methods: GET

company_controller_readbyNameLike:
    path: /company/readCompany/like/{name}
    controller: App\Controller\CompanyController::readCompanyByNameLike
    methods: GET

company_controller_update:
    path: /company/updateCompany/{id}
    controller: App\Controller\CompanyController::updateCompany
    methods: PUT

company_controller_delete:
    path: /company/deleteCompany/{id}
    controller: App\Controller\CompanyController::deleteCompany
    methods: DELETE